# Generated by Django 5.2.12 on 2026-04-01 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('is_phishing', models.CharField(choices=[('위험', 'LOW'), ('안전', 'HIGH')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('travel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_results', to='travels.travel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
