# Generated by Django 5.2.12 on 2026-04-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='explanation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
